"""add gender and eye_color to character

Revision ID: 552f700bb62b
Revises: a445f520b305
Create Date: 2025-07-30 09:43:55.315982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552f700bb62b'
down_revision = 'a445f520b305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=20), nullable=False))

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('climate', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('terrain', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('population', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('population')
        batch_op.drop_column('terrain')
        batch_op.drop_column('climate')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('eye_color')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
